// <auto-generated />
using CNode.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CNode.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210318161131_GitToolsTest")]
    partial class GitToolsTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CNode.Domain.Entities.GitAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("GitToolId")
                        .HasColumnType("integer")
                        .HasColumnName("git_tool_id");

                    b.Property<int>("GitUserId")
                        .HasColumnType("integer")
                        .HasColumnName("git_user_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_git_accounts");

                    b.HasIndex("GitToolId")
                        .HasDatabaseName("ix_git_accounts_git_tool_id");

                    b.HasIndex("GitUserId", "GitToolId")
                        .IsUnique()
                        .HasDatabaseName("ix_git_accounts_git_user_id_git_tool_id");

                    b.ToTable("git_accounts");
                });

            modelBuilder.Entity("CNode.Domain.Entities.GitTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_git_tools");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_git_tools_name");

                    b.ToTable("git_tools");
                });

            modelBuilder.Entity("CNode.Domain.Entities.GitAccount", b =>
                {
                    b.HasOne("CNode.Domain.Entities.GitTool", "GitTool")
                        .WithMany("GitUsers")
                        .HasForeignKey("GitToolId")
                        .HasConstraintName("fk_git_accounts_git_tools_git_tool_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitTool");
                });

            modelBuilder.Entity("CNode.Domain.Entities.GitTool", b =>
                {
                    b.Navigation("GitUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
