// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GitNode.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210408204241_FixTheAccountTable")]
    partial class FixTheAccountTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CNode.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OriginId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_id");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer")
                        .HasColumnName("platform_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("PlatformId")
                        .HasDatabaseName("ix_accounts_platform_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_accounts_user_id");

                    b.HasIndex("OriginId", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_origin_id_platform_id");

                    b.HasIndex("Token", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_token_platform_id");

                    b.HasIndex("Username", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username_platform_id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_platforms_name");

                    b.ToTable("platforms");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OriginId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_id");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_name");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_url");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<bool>("Share")
                        .HasColumnType("boolean")
                        .HasColumnName("share");

                    b.HasKey("Id")
                        .HasName("pk_repositories");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_repositories_account_id");

                    b.HasIndex("Name", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_repositories_name_account_id");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("TechnologyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("technology_type_id");

                    b.HasKey("Id")
                        .HasName("pk_technologies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_technologies_name");

                    b.HasIndex("TechnologyTypeId")
                        .HasDatabaseName("ix_technologies_technology_type_id");

                    b.ToTable("technologies");
                });

            modelBuilder.Entity("CNode.Domain.Entities.TechnologyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("NamePlural")
                        .HasColumnType("text")
                        .HasColumnName("name_plural");

                    b.HasKey("Id")
                        .HasName("pk_technology_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_technology_types_name");

                    b.HasIndex("NamePlural")
                        .IsUnique()
                        .HasDatabaseName("ix_technology_types_name_plural");

                    b.ToTable("technology_types");
                });

            modelBuilder.Entity("CNode.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("RepositoryTechnology", b =>
                {
                    b.Property<int>("RepositoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("repositories_id");

                    b.Property<int>("TechnologiesId")
                        .HasColumnType("integer")
                        .HasColumnName("technologies_id");

                    b.HasKey("RepositoriesId", "TechnologiesId")
                        .HasName("pk_repository_technology");

                    b.HasIndex("TechnologiesId")
                        .HasDatabaseName("ix_repository_technology_technologies_id");

                    b.ToTable("repository_technology");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Account", b =>
                {
                    b.HasOne("CNode.Domain.Entities.Platform", "Platform")
                        .WithMany("Accounts")
                        .HasForeignKey("PlatformId")
                        .HasConstraintName("fk_accounts_platforms_platform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNode.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_accounts_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Repository", b =>
                {
                    b.HasOne("CNode.Domain.Entities.Account", "Account")
                        .WithMany("Repositories")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_repositories_accounts_account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Technology", b =>
                {
                    b.HasOne("CNode.Domain.Entities.TechnologyType", "TechnologyType")
                        .WithMany("Technologies")
                        .HasForeignKey("TechnologyTypeId")
                        .HasConstraintName("fk_technologies_technology_types_technology_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnologyType");
                });

            modelBuilder.Entity("RepositoryTechnology", b =>
                {
                    b.HasOne("CNode.Domain.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoriesId")
                        .HasConstraintName("fk_repository_technology_repositories_repositories_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNode.Domain.Entities.Technology", null)
                        .WithMany()
                        .HasForeignKey("TechnologiesId")
                        .HasConstraintName("fk_repository_technology_technologies_technologies_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNode.Domain.Entities.Account", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("CNode.Domain.Entities.Platform", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CNode.Domain.Entities.TechnologyType", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("CNode.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
